#@data/values-schema
---
name: briq-protocol
env: test
storage_bucket: briq-bucket-test-1
static_ip: lb-sltech-company-ipv4-1
sites: [""]
resources:
  cpu: "50m"
  memory: "128Mi"
image_name: briq-protocol
image_tag: ""
