#@data/values
---
name: briq-protocol
env: prod
storage_bucket: briq-bucket-prod-1
static_ip: lb-sltech-company-ipv4-1
sites: ["api.briq.construction", "api.sltech.company"]

indexer:
  name: dev-briq-indexer
  image_store: mongo:latest
  indexer_id: "kub-test-1"
  network_name: 'starknet-goerli'
  start_block: '375000'
  resources:
    cpu_store: "50m"
    memory_store: "128Mi"
    cpu_apibara: "50m"
    memory_apibara: "128Mi"
    cpu_runner: "50m"
    memory_runner: "128Mi"
