#@ load("@ytt:data", "data")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: #@ data.values.job_name
spec:
  template:
    metadata:
      labels:
        app: #@ data.values.job_name
    spec:
      serviceAccountName: #@ data.values.service_account
      containers:
      - name: #@ data.values.job_name
        image: #@ "europe-west3-docker.pkg.dev/healthy-saga-329513/sltech-briq/" + data.values.image_name + ":" + data.values.image_tag
        command: #@ ["python3", data.values.job]
        env:
        - name: CLOUD_STORAGE_BUCKET
          value: #@ data.values.storage_bucket
      restartPolicy: OnFailure
  backoffLimit: 4
