#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.name
  annotations:
    cloud.google.com/backend-config: #@ '{"default": "' + data.values.name + '"}'
spec:
  selector:
    app: #@ data.values.name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: #@ data.values.name
spec:
  timeoutSec: 60
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    port: 5000
    type: HTTP
    requestPath: /health
