[admin.storage]
connection_string = "mongodb://apibara:apibara@mongo:27017"
[network.starknet-goerli]
type = "starknet"
provider_url = "https://starknet-goerli.apibara.com/"
[network.starknet-devnet]
type = "starknet-gateway"
gateway_url = "http://host.docker.internal:5050/gateway"
feeder_gateway_url = "http://host.docker.internal:5050/feeder_gateway"
